# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: gcc
stages:  
  - check_merge        # List of stages for jobs, and their order of execution
  - build
  - test

before_script:
  - apt update
  - apt install -y autotools-dev autoconf libcriterion-dev python3 python3-pyyaml-env-tag python3-termcolor

check_merge-job:
  stage: check_merge
  script:
    - git fetch origin master
    - git checkout master
    - git pull origin master
    - git merge-base --is-ancestor $CI_COMMIT_SHA origin/master || exit 1
  only:
    - master

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - autoreconf -i
    - ./configure
    - make
  only:
    - master

test-job:   # This job also runs in the test stage.
  stage: test
  script:
    - autoreconf -i
    - ./configure
    - make check
  only:
    - master
